# Generated by Django 3.2.10 on 2021-12-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vittlesapi', '0003_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familybook',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='vittlesapi.family'),
        ),
        migrations.AlterField(
            model_name='familybook',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='vittlesapi.recipe'),
        ),
    ]
